---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ics-operators-manager-role
rules:
- apiGroups:
  - admin.ceph.ics.cloud
  resources:
  - users
  - users/finalizers
  - users/status
  - keypairs
  - keypairs/finalizers
  - keypairs/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keystone.openstack.ics.cloud
  resources:
  - projects
  - projects/finalizers
  - projects/status
  - groups
  - groups/finalizers
  - groups/status
  - users
  - users/finalizers
  - users/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - neutron.openstack.ics.cloud
  resources:
  - rbacpolicies
  - rbacpolicies/finalizers
  - rbacpolicies/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - minio.ics.cloud
  resources:
  - buckets
  - buckets/finalizers
  - buckets/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
